### ISSUE TITLE
Users getting InsufficientAccountLiquidity error when trying to purchase

### ISSUE THREAD

**Issue by Mateo-Soso** [exactly/exa#206]
The user added enough funds for the transaction and they were correctly poked into his account.
When trying to make a credit purchase he got a rejection.

[Sentry trace](https://exactly.sentry.io/performance/trace/6c346adc8db763f70e95c9de61b9d5c5/?end=2024-11-28T13%3A11%3A55&environment=production&node=txn-a01b11813a7a45d4a640f12f1e61adc6&pageEnd=2024-11-28T13%3A11%3A55.000&pageStart=2024-11-28T13%3A09%3A36.000&project=4506186349674496&source=traces&start=2024-11-28T13%3A09%3A36&targetId=187ff7f61a6feb86&timestamp=1732799486)

[Sentry issue ](https://exactly.sentry.io/issues/6020440024/events/bb6e5f8b4e6b49bd812a4940c7a4fb60/)

**Comment by nfmelendez** [comment]
Display of all errors of this type:

https://exactly.sentry.io/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=Error%3A%20InsufficientAccountLiquidity&project=4506186349674496&query=issue%3AMOBILE-4M&queryDataset=error-events&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29

**Comment by nfmelendez** [comment]
Nov-06-2024 10:06:17 AM UTC transfer +0.007 ETH
Nov-28-2024 12:10:57 PM +UTC transfer +0.078 ETH
Nov-28-2024 12:42:43 PM +UTC withdraw -0.078 ETH
Nov-28-2024 01:00:33 PM +UTC collect credit 1.64 USDC
**2024-11-28T13:11:25.393Z AUTHORIZTION DECLINED: 15.78 USD**
Nov-28-2024 01:55:25 PM +UTC withdraw -0.0045 ETH

**Comment by nfmelendez** [comment]
```solidity
    // SPDX-License-Identifier: UNLICENSED
pragma solidity 0.8.10;

import "forge-std/Test.sol";
import "./../interface.sol";


interface IExaAccount {


  function collectCredit(uint256 maturity, uint256 amount, uint256 timestamp, bytes calldata signature) external;
 function accountLiquidity(
    address account,
    address marketToSimulate,
    uint256 withdrawAmount
  ) external  returns (uint256 sumCollateral, uint256 sumDebtPlusEffects) ;
}

contract ContractTest is Test {
    address user = 0x1C5a7f61b07DD43F394b5B02aBeb8FcA52814E26;
    address keeper = 0xcDdB23654595C224A563f62943D9Ff189138c04e;

    function setUp() public {
         vm.createSelectFork("optimism",  128_600_355); //fork optimism at block 128600355
    }

    function testOPAccountLiquidity() public {
      vm.prank(keeper);
      IExaAccount(user).collectCredit(1734566400, 15780000, 1732799485, hex"c2a988d9088815e0d0d07b51839b358e22fa8ff95f871f50c8edb2caa1e5ca023b6b0072d90483234b19bdd76002d9f93bded4439afb4c5e7b5cf481d74bdfbe1b");
    }
}

```
